apiVersion: v1
kind: Service
metadata:
  name: litellm
  namespace: ${MAAS_NS}
  labels:
    app: litellm
spec:
  type: ClusterIP
  selector:
    app: litellm
  ports:
    - name: http
      port: 8080
      targetPort: 4000
      appProtocol: http
