apiVersion: v1
kind: Namespace
metadata:
  name: ${MAAS_NS}
  labels:
    opendatahub.io/dashboard: "true"
    modelmesh-enabled: "false"
  annotations:
    openshift.io/display-name: "MaaS External Models"
